apiVersion: v1
kind: Pod
metadata:
  name: busybox-app
  labels:
    app: busybox-app
spec:
  containers:
  - name: container1
    image: busybox
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']
  - name: container2
    image: busybox
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']
