apiVersion: v1
kind: Pod
metadata:
  name: configmap-mounted-pod
spec:
  volumes:
  - name: data
    configMap:
      name: cluster-info
  containers:
  - name: centos
    image: docker.io/centos
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']
    volumeMounts:
    - name: data
      mountPath: /etc/configmap-volume
