apiVersion: v1
kind: Pod
metadata:
  name: internal-volume-pod
  labels:
    app: internal-volume-pod
spec:
  volumes:
  - name: data
    emptyDir: {}
  initContainers:
  - name: init-centos
    image: docker.io/centos
    volumeMounts:
    - name: data
      mountPath: /usr/local/apache2/htdocs/centos1/
    command: ['sh', '-c', 'echo Hello to Centos1 > /usr/local/apache2/htdocs/centos1/index.html']
  containers:
  - name: centos1
    image: httpd
    #command: ['sh', '-c', 'echo The app is running! && sleep 3600']
    volumeMounts:
    - name: data
      mountPath: /usr/local/apache2/htdocs/centos1/
