apiVersion: v1
kind: Pod
metadata:
  name: ingress-path-pod2
  labels:
    app: ingress-path-pod2
spec:
  volumes:
  - name: data2
    emptyDir: {}
  initContainers:
  - name: init-centos
    image: docker.io/centos
    volumeMounts:
    - name: data2
      mountPath: /usr/local/apache2/htdocs/centos2/
    command: ['sh', '-c', 'echo Hello to Cento2 > /usr/local/apache2/htdocs/centos2/index.html']
  containers:
  - name: web2
    image: httpd
    #command: ['sh', '-c', 'echo The app is running! && sleep 3600']
    volumeMounts:
    - name: data2
      mountPath: /usr/local/apache2/htdocs/centos2/
