apiVersion: v1
kind: Pod
metadata:
  name: internal-volume-pod2
  labels:
    app: internal-volume-pod2
spec:
  volumes:
  - name: data2
    emptyDir: {}
  initContainers:
  - name: init-centos
    image: docker.io/centos
    volumeMounts:
    - name: data2
      mountPath: /usr/local/apache2/htdocs/centos2/
    command: ['sh', '-c', 'echo Hello to Cento2 > /usr/local/apache2/htdocs/centos2/index.html']
  containers:
  - name: centos1
    image: httpd
    #command: ['sh', '-c', 'echo The app is running! && sleep 3600']
    volumeMounts:
    - name: data2
      mountPath: /usr/local/apache2/htdocs/centos2/
