apiVersion: v1
kind: Pod
metadata:
  name: internal-volume-pod
spec:
  volumes:
  - name: data
    emptyDir: {}
  containers:
  - name: centos1
    image: docker.io/centos
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']
    volumeMounts:
    - name: data
      mountPath: /centos1
  - name: centos2
    image: docker.io/centos
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']
    volumeMounts:
    - name: data
      mountPath: /centos2
