apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: pod1-to-pod2
spec:
  podSelector:
    matchLabels:
      app: pod1
  policyTypes:
  - Egress
  egress:
  - ports:
    - port: 53
      protocol: UDP
    - port: 53
      protocol: TCP
  - to:
    - podSelector:
        matchLabels:
          app: pod2
