apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: pod1-from-pod2
spec:
  podSelector:
    matchLabels:
      app: pod1
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: pod2
