apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv-storageclass
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs2
  nfs:
    path: /k8snfs2
    server: 172.24.0.165
    readOnly: false
