apiVersion: "v1"
kind: "LimitRange"
metadata:
 name: "prod-limits"
spec:
 limits:
  - type: "Pod"
    max:
     cpu: "250m"
     memory: "128Mi"
    min:
        cpu: "200m"
        memory: "6Mi"
  - type: "Container"
    default:
     cpu: "250m"
     memory: "128Mi"
