apiVersion: v1
kind: ResourceQuota
## Resource Type
metadata:
  name: dev-quota
## Quota Name
spec:
  hard:
## Object Resource Quota 
    services: "10"
## Compute Resource Quota 
    cpu: "1300m"
    memory: "1.5Gi"
