apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replicaset-nginx
  labels:
    app: ngnix
    tier: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: prod
  template:
    metadata:
      labels:
        tier: prod
    spec:
      containers:
      - name: nginx
        image: docker.io/nginx
