apiVersion: v1
kind: Pod
metadata:
  name: secret-mounted-pod
spec:
  volumes:
  - name: data
    secret:
      secretName: mysql
  containers:
  - name: centos
    image: docker.io/centos
    command: ['sh', '-c', 'echo The app is running! && sleep 3600']
    volumeMounts:
    - name: data
      mountPath: /etc/secret-volume
